In [2]:
import numpy as np

def gradient_descent_regression(X, y, lr=0.0001, batch_size=1, num_epochs=30):
    n = len(y)
    beta = np.zeros(X.shape[1])
    losses = []
    for epoch in range(num_epochs):
        # Shuffle examples, keeping X and y aligned
        perms = np.random.permutation(n)
        X_epoch = X[perms]
        y_epoch = y[perms]

        print(f"<<< EPOCH -> (epoch) >>>")

        for i in range(0, n, batch_size):
            X_sec = X_epoch[i:i + batch_size]
            y_sec = y_epoch[i:i + batch_size]

            # Forward pass
            pred = X_sec @ beta

            # Prediction error
            err = pred - y_sec

            # Gradient of batch MSE
            m = len(y_sec)
            grads = (2 / m) * X_sec.T @ err

            # Update coefficients
            beta -= lr * grads

            # track losses
            loss = np.mean((X @ beta - y)**2)
            losses.append(loss)
    print("<<< finished >>>")
    return beta, losses

In [3]:
def sigmoid(z):
    return (1 / 1 + np.exp(
        np.clip(z, -500, 500)
    ))

def gradient_descent_logistic(
    X,
    y,
    lr = 0.001,
    num_epochs = 10,
    batch_size = 1):
    x = np.asarray(X, dtype=float)
    y = np.asarray(y, dtype=float).reshape(-1)
    n = len(y)
    losses = []
    beta = np.zeros(X.shape[1])
    for epoch in range(num_epochs):
        perms = np.random.permutation(n)
        x, y  = x[perms], y[perms]
        for i in range(0, n, batch_size):
            xi = x[i:i+batch_size]
            yi = y[i:i+batch_size]

            # get predictions and error
            preds = sigmoid(xi @ beta)
            err = preds - yi
            
            # gradients
            grads = xi.T.dot(err).flatten()
            beta  = beta - lr * grads 

            # loss
            p = sigmoid(x.T.dot(beta))
            loss = -np.mean(
                y * np.log(p + 1e-15) + (1 - y) * np.log(1 - p + 1e-15)
            )
            
            losses.append(loss)
    return beta, losses

In [4]:
Data ={ 
    "X1": [
        15,16,17,19,25,26,30,35,45,55
    ],
    "X2": [
        39,81,6,77,40,70,88,29,85,52
    ]
}

In [5]:
import pandas as pd
df = pd.DataFrame(Data)

In [6]:
df

   X1  X2
0  15  39
1  16  81
2  17   6
3  19  77
4  25  40
5  26  70
6  30  88
7  35  29
8  45  85
9  55  52

In [7]:
import numpy as np
def get_distance(p1, p2):
    
    return np.linalg.norm(np.asarray(p1) - np.asarray(p2))

In [8]:
points = [
    (15,39), (16,81), (17,6), (19,77), (25,40), (26,70), (30,88), (35,29), (45,85), (55,52)
]

def get_dist_df(points, k:int = 1):
    dists = {}
    if k == 1:
        c = [(30, 88)]
    if k == 2:
        c = [(25,40), (45,85)]
    if k == 3:
        c = [(16,81), (19,77), (55,52)]
    if k == 4:
        c = [(15,39), (17,6), (26,70), (35,29)]
    for i,c_ in enumerate(c):    
        dists[f"c_{i}"] = [
            get_distance(x, c_) for x in points 
        ]
    return pd.DataFrame(dists)

In [9]:
df_1 = get_dist_df(points, k = 1)

In [10]:
df_1

         c_0
0  51.244512
1  15.652476
2  83.024093
3  15.556349
4  48.259714
5  18.439089
6   0.000000
7  59.211485
8  15.297059
9  43.829214

In [11]:
df_2 = get_dist_df(points, k = 2)

In [12]:
df_2

         c_0        c_1
0  10.049876  54.918121
1  41.976184  29.274562
2  34.928498  83.815273
3  37.483330  27.202941
4   0.000000  49.244289
5  30.016662  24.207437
6  48.259714  15.297059
7  14.866069  56.885851
8  49.244289   0.000000
9  32.310989  34.481879

In [13]:
df_points = pd.DataFrame(points)

In [14]:
df_points.columns = ["x", "y"]

In [15]:
df_points

    x   y
0  15  39
1  16  81
2  17   6
3  19  77
4  25  40
5  26  70
6  30  88
7  35  29
8  45  85
9  55  52

In [16]:
def assign_clusters(dist_df):
    return dist_df.values.argmin(axis=1)

In [17]:
cluster = assign_clusters(df_2)

In [18]:
cluster

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0])

In [29]:
def kmeans(points, k, n_iter = 100):
    points = np.array(points)
    for i in range(n_iter):
        df = get_dist_df(points, k = k)
        labels = assign_clusters(df)

        centroids = [
            points[labels == j].mean(axis = 0).tolist()
            for j in range(k)
        ]
    
    return labels, centroids

In [33]:
l, c = kmeans(points, k = 4, n_iter=100)

In [34]:
l

array([0, 2, 1, 2, 0, 2, 2, 3, 2, 3])

In [35]:
c

[[20.0, 39.5], [17.0, 6.0], [27.2, 80.2], [45.0, 40.5]]